# Generated by Django 4.2.16 on 2024-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_nm', models.CharField(max_length=15)),
                ('last_nm', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
    ]
